// Renders a student-facing lesson-report PDF from a session, using pdf-lib.
// Server-only; called from the "Confirm & send" Server Action and attached to
// the student's email.
//
// Styled like the site and the emails (the "Bumble note - social media
// templates" pack): the logo lockup, Fraunces headings over Hanken Grotesk
// text, cocoa ink, butter and powder-blue fields. The page itself stays white
// and the fills stay pale, because students print these.
//
// The fonts and logo come from src/lib/pdf-assets.ts (generated by
// scripts/build-pdf-assets.ts), so nothing is read from disk at runtime.

import fontkit from "@pdf-lib/fontkit";
import { PDFDocument, rgb, type PDFFont, type PDFPage, type RGB } from "pdf-lib";
import type { Session, Student } from "./mock";
import * as assets from "./pdf-assets";

const A4: [number, number] = [595.28, 841.89];
const [W, H] = A4;
const MARGIN = 48;
/** Content stops here, leaving room for the footer. */
const BOTTOM = 70;
const CONTENT_W = W - MARGIN * 2;

/** The social-kit palette, as in globals.css (.theme-bn) and the emails. */
const hex = (h: string) =>
  rgb(parseInt(h.slice(1, 3), 16) / 255, parseInt(h.slice(3, 5), 16) / 255, parseInt(h.slice(5, 7), 16) / 255);
const C = {
  cocoa: hex("#412e28"),
  soft: hex("#6b5245"),
  muted: hex("#8a7466"),
  line: hex("#eadfce"),
  butter: hex("#fff0b5"),
  butterSoft: hex("#fff7d9"),
  sky: hex("#c1d9e6"),
  skySoft: hex("#e4eff5"),
  skyDeep: hex("#2f5d7c"),
  white: rgb(1, 1, 1),
};

type Fonts = { display: PDFFont; displayItalic: PDFFont; reg: PDFFont; bold: PDFFont; italic: PDFFont };

// The fonts cover Latin text, which is nearly everything a lesson produces.
// Anything they can't draw (an IPA symbol, an arrow, an emoji) is swapped for a
// readable stand-in or "?", so one stray character never breaks the PDF.
const REPLACE: Record<string, string> = {
  "→": "->", "←": "<-", "↔": "<->", "⟶": "->", "⇒": "=>", "⟹": "=>",
  "≥": ">=", "≤": "<=", "×": "x", "…": "...", "\t": "  ",
  // Common English-teaching IPA → student-friendly forms.
  "θ": "th", "ð": "th", "ʃ": "sh", "ʒ": "zh", "ŋ": "ng",
  "æ": "a", "ə": "uh", "ɪ": "i", "ʊ": "u", "ɒ": "o", "ɔ": "aw", "ʌ": "u",
  "ɜ": "er", "ɑ": "ah", "ɡ": "g", "ʔ": "'", "ː": "", "ˈ": "'", "ˌ": "",
};

const charSets = new WeakMap<PDFFont, Set<number>>();
function supports(font: PDFFont, cp: number): boolean {
  let set = charSets.get(font);
  if (!set) charSets.set(font, (set = new Set(font.getCharacterSet())));
  return set.has(cp);
}

function sanitize(input: string, font: PDFFont): string {
  // Word by word: the fonts have a few IPA symbols but not most, so a word the
  // font can't draw whole is simplified whole ("/θɪŋk/" → "/think/", never a
  // half-converted "/thiŋk/"). A word it can draw whole is left as written.
  return input
    .split(/(\s+)/)
    .map((word) => {
      if ([...word].every((ch) => /\s/.test(ch) || supports(font, ch.codePointAt(0)!))) return word;
      // Affricate digraphs first (two code points → one friendly form).
      const simple = [...word.replace(/tʃ/g, "ch").replace(/dʒ/g, "j")]
        .map((ch) => REPLACE[ch] ?? ch)
        .join("");
      let out = "";
      for (const ch of simple) {
        if (supports(font, ch.codePointAt(0)!)) out += ch;
        else {
          // An accented letter the font lacks still reads fine without the accent.
          const base = ch.normalize("NFD")[0];
          out += base !== ch && supports(font, base.codePointAt(0)!) ? base : "?";
        }
      }
      return out;
    })
    .join("");
}

/** Split text into lines that fit `maxWidth`, honouring explicit newlines. */
function wrap(raw: string, font: PDFFont, size: number, maxWidth: number): string[] {
  const text = sanitize(raw, font);
  const out: string[] = [];
  for (const para of text.split("\n")) {
    const words = para.split(/\s+/).filter(Boolean);
    if (words.length === 0) {
      out.push("");
      continue;
    }
    let line = "";
    for (const word of words) {
      const candidate = line ? `${line} ${word}` : word;
      if (font.widthOfTextAtSize(candidate, size) > maxWidth && line) {
        out.push(line);
        line = word;
      } else {
        line = candidate;
      }
    }
    if (line) out.push(line);
  }
  return out;
}

/** A run of wrapped text, measured: draw it with its top edge at `top`. */
type TextRun = { lines: string[]; font: PDFFont; size: number; lh: number; color: RGB; height: number };

function run(str: string, font: PDFFont, size: number, lh: number, color: RGB, width: number): TextRun {
  const lines = wrap(str, font, size, width);
  return { lines, font, size, lh, color, height: lines.length * lh };
}

function drawRun(page: PDFPage, r: TextRun, x: number, top: number) {
  r.lines.forEach((line, i) => {
    // Baseline sits a little below the middle of each line box.
    const baseline = top + i * r.lh + r.lh / 2 + r.size * 0.33;
    page.drawText(line, { x, y: H - baseline, size: r.size, font: r.font, color: r.color });
  });
}

/** Rounded rectangle by its top-left corner, in top-down page coordinates. */
function roundRect(
  page: PDFPage,
  x: number,
  top: number,
  w: number,
  h: number,
  r: number,
  o: { fill?: RGB; border?: RGB },
) {
  r = Math.min(r, h / 2, w / 2);
  const path =
    `M ${r} 0 H ${w - r} Q ${w} 0 ${w} ${r} V ${h - r} Q ${w} ${h} ${w - r} ${h} ` +
    `H ${r} Q 0 ${h} 0 ${h - r} V ${r} Q 0 0 ${r} 0 Z`;
  page.drawSvgPath(path, {
    x,
    y: H - top,
    color: o.fill,
    borderColor: o.border,
    borderWidth: o.border ? 0.75 : 0,
  });
}

/** Small uppercase label with letter-spacing, as on the site's eyebrows. */
function tracked(page: PDFPage, text: string, x: number, top: number, font: PDFFont, size: number, color: RGB, align: "left" | "right" = "left") {
  const s = sanitize(text.toUpperCase(), font);
  const spacing = size * 0.12;
  const width = [...s].reduce((w, ch) => w + font.widthOfTextAtSize(ch, size) + spacing, -spacing);
  let cx = align === "right" ? x - width : x;
  for (const ch of s) {
    page.drawText(ch, { x: cx, y: H - top - size, size, font, color });
    cx += font.widthOfTextAtSize(ch, size) + spacing;
  }
}

/** A measured piece of a panel or list: its height, and how to draw it at `top`. */
type Row = { height: number; draw: (page: PDFPage, top: number) => void };

export function renderLessonReportPDF(
  session: Session,
  student: Student,
  opts: { tutorName: string },
): Promise<Uint8Array> {
  return build(session, student, opts);
}

async function build(session: Session, student: Student, opts: { tutorName: string }): Promise<Uint8Array> {
  const doc = await PDFDocument.create();
  doc.registerFontkit(fontkit);
  const embed = (b64: string) => doc.embedFont(Buffer.from(b64, "base64"), { subset: true });
  const fonts: Fonts = {
    display: await embed(assets.frauncesRegular),
    displayItalic: await embed(assets.frauncesItalic),
    reg: await embed(assets.hankenRegular),
    bold: await embed(assets.hankenBold),
    italic: await embed(assets.hankenItalic),
  };
  const logo = await doc.embedPng(Buffer.from(assets.logoLockup, "base64"));

  const topic = session.title.includes("·") ? session.title.split("·").slice(1).join("·").trim() : session.title;
  const tutorFirst = opts.tutorName.trim().split(/\s+/)[0] ?? "";
  doc.setTitle(`${topic} - lesson notes`);
  doc.setAuthor(opts.tutorName);
  doc.setCreator("BumbleNote");

  let page = doc.addPage(A4);
  let y = MARGIN; // cursor: distance from the top of the page

  function newPage() {
    page = doc.addPage(A4);
    y = MARGIN;
  }
  /** Start a new page unless `space` still fits on this one. */
  function ensure(space: number) {
    if (y + space > H - BOTTOM) newPage();
  }

  // ---- Header ----
  page.drawImage(logo, { x: MARGIN, y: H - y - 48, width: 84, height: 48 });
  tracked(page, "Lesson notes", W - MARGIN, y + 10, fonts.bold, 8, C.skyDeep, "right");
  const dateRun = run(session.date, fonts.reg, 10.5, 14, C.soft, 200);
  const dateW = fonts.reg.widthOfTextAtSize(dateRun.lines[0] ?? "", 10.5);
  drawRun(page, dateRun, W - MARGIN - dateW, y + 22);
  y += 48 + 20;

  const title = run(topic, fonts.display, 30, 35, C.cocoa, CONTENT_W);
  drawRun(page, title, MARGIN, y);
  y += title.height + 4;
  const sub = run(`${student.name}  ·  with ${opts.tutorName}`, fonts.reg, 11.5, 16, C.soft, CONTENT_W);
  drawRun(page, sub, MARGIN, y);
  y += sub.height + 14;
  page.drawRectangle({ x: MARGIN, y: H - y - 3, width: CONTENT_W, height: 3, color: C.sky });
  y += 3 + 18;

  // ---- Snapshot tiles ----
  const TILE_GAP = 10;
  const tileW = (CONTENT_W - TILE_GAP * 2) / 3;
  const TILE_H = 64;
  const tiles: { label: string; value: string; bar?: number }[] = [
    { label: "Your speaking time", value: `${session.talkTime.student}%`, bar: session.talkTime.student },
    { label: "New words", value: String(session.vocab.length) },
    { label: "Lesson length", value: `${session.durationMin} min` },
  ];
  tiles.forEach((t, i) => {
    const x = MARGIN + i * (tileW + TILE_GAP);
    roundRect(page, x, y, tileW, TILE_H, 10, { fill: C.skySoft });
    tracked(page, t.label, x + 14, y + 12, fonts.bold, 7, C.skyDeep);
    drawRun(page, run(t.value, fonts.display, 22, 26, C.cocoa, tileW - 28), x + 14, y + 22);
    if (t.bar !== undefined) {
      const barW = tileW - 28;
      const pct = Math.max(0, Math.min(100, t.bar)) / 100;
      roundRect(page, x + 14, y + TILE_H - 13, barW, 5, 2.5, { fill: C.white });
      if (pct > 0) roundRect(page, x + 14, y + TILE_H - 13, Math.max(5, barW * pct), 5, 2.5, { fill: C.cocoa });
    }
  });
  y += TILE_H;

  // ---- Building blocks ----

  /** Section heading, kept on the same page as at least `keepWith` of what follows. */
  function heading(label: string, keepWith: number) {
    const r = run(label, fonts.display, 18, 22, C.cocoa, CONTENT_W);
    y += 24;
    ensure(r.height + 10 + keepWith);
    drawRun(page, r, MARGIN, y);
    y += r.height + 10;
  }

  /**
   * A filled panel of rows. A panel too long for the rest of the page carries
   * on at the top of the next one, with its own background there.
   */
  function panel(rows: Row[], fill: RGB, pad = { x: 18, y: 14 }) {
    let i = 0;
    while (i < rows.length) {
      const avail = H - BOTTOM - y - pad.y * 2;
      let used = 0;
      let n = 0;
      while (i + n < rows.length && used + rows[i + n].height <= avail) {
        used += rows[i + n].height;
        n++;
      }
      if (n === 0) {
        if (y > MARGIN) {
          newPage();
          continue;
        }
        used = rows[i].height; // taller than a whole page: draw it anyway
        n = 1;
      }
      roundRect(page, MARGIN, y, CONTENT_W, used + pad.y * 2, 10, { fill });
      let top = y + pad.y;
      for (const row of rows.slice(i, i + n)) {
        row.draw(page, top);
        top += row.height;
      }
      y += used + pad.y * 2;
      i += n;
      if (i < rows.length) newPage();
    }
  }

  /** Bulleted rows for a panel: a cocoa dot ringed in the panel's accent. */
  function bulletRows(items: string[], ring: RGB, x = MARGIN + 18, width = CONTENT_W - 36): Row[] {
    return items.map((item, i) => {
      const r = run(item, fonts.reg, 10.5, 15.5, C.cocoa, width - 16);
      const gap = i < items.length - 1 ? 6 : 0;
      return {
        height: r.height + gap,
        draw: (p, top) => {
          p.drawCircle({ x: x + 4, y: H - top - 7.75, size: 4, color: C.cocoa, borderColor: ring, borderWidth: 2 });
          drawRun(p, r, x + 16, top);
        },
      };
    });
  }

  // ---- Vocabulary: two cards per row ----
  if (session.vocab.length) {
    const COL_GAP = 12;
    const PAD = 12;
    const colW = (CONTENT_W - COL_GAP) / 2;
    const inner = colW - PAD * 2;
    const card = (v: (typeof session.vocab)[number]) => {
      const parts = [
        run(v.term, fonts.bold, 11.5, 15, C.cocoa, inner),
        ...(v.meaning ? [run(v.meaning, fonts.reg, 10, 14, C.soft, inner)] : []),
        ...(v.example ? [run(`“${v.example}”`, fonts.displayItalic, 10.5, 14.5, C.muted, inner)] : []),
      ];
      return { parts, height: PAD * 2 + parts.reduce((h, p) => h + p.height, 0) + (parts.length - 1) * 3 };
    };
    const pairs: ReturnType<typeof card>[][] = [];
    for (let i = 0; i < session.vocab.length; i += 2) pairs.push(session.vocab.slice(i, i + 2).map(card));

    const rowH = (pair: ReturnType<typeof card>[]) => Math.max(...pair.map((c) => c.height));
    heading("New vocabulary", rowH(pairs[0]));
    pairs.forEach((pair, i) => {
      const h = rowH(pair);
      if (i > 0) y += 10;
      ensure(h);
      pair.forEach((c, col) => {
        const x = MARGIN + col * (colW + COL_GAP);
        roundRect(page, x, y, colW, h, 8, { fill: C.white, border: C.line });
        let top = y + PAD;
        for (const part of c.parts) {
          drawRun(page, part, x + PAD, top);
          top += part.height + 3;
        }
      });
      y += h;
    });
  }

  // ---- What went well / areas to improve ----
  // Usually a few short points each, so they sit side by side; stacked when
  // only one is there, or when side by side would be taller than a page.
  const wellFocus = [
    { label: "What went well", items: session.wentWell, fill: C.skySoft, ring: C.sky },
    { label: "Areas to improve", items: session.focus, fill: C.butterSoft, ring: C.butter },
  ].filter((s) => s.items.length);
  const COL_GAP = 12;
  const halfW = (CONTENT_W - COL_GAP) / 2;
  const PAD = { x: 16, y: 14 };
  const columns = wellFocus.map((s, col) => {
    const x = MARGIN + col * (halfW + COL_GAP);
    const rows = bulletRows(s.items, s.ring, x + PAD.x, halfW - PAD.x * 2);
    return { ...s, x, rows, height: rows.reduce((h, r) => h + r.height, 0) + PAD.y * 2 };
  });
  const sideBySideH = 32 + Math.max(0, ...columns.map((c) => c.height));
  if (columns.length === 2 && sideBySideH <= H - BOTTOM - MARGIN - 24) {
    y += 24;
    ensure(sideBySideH);
    const boxH = Math.max(...columns.map((c) => c.height));
    for (const c of columns) {
      drawRun(page, run(c.label, fonts.display, 18, 22, C.cocoa, halfW), c.x, y);
      roundRect(page, c.x, y + 32, halfW, boxH, 10, { fill: c.fill });
      let top = y + 32 + PAD.y;
      for (const r of c.rows) {
        r.draw(page, top);
        top += r.height;
      }
    }
    y += sideBySideH;
  } else {
    for (const s of wellFocus) {
      const rows = bulletRows(s.items, s.ring);
      heading(s.label, rows[0].height + 28);
      panel(rows, s.fill);
    }
  }

  // ---- Homework ----
  if (session.homework.trim()) {
    const r = run(session.homework, fonts.reg, 11, 16, C.cocoa, CONTENT_W - 36);
    const rows: Row[] = r.lines.map((line) => ({
      height: r.lh,
      draw: (p, top) => drawRun(p, { ...r, lines: [line], height: r.lh }, MARGIN + 18, top),
    }));
    heading("Homework", r.lh * Math.min(2, r.lines.length) + 28);
    panel(rows, C.butter);
  }

  // ---- A note from the tutor ----
  if (session.additionalInfo.trim()) {
    const r = run(session.additionalInfo, fonts.displayItalic, 12.5, 18, C.cocoa, CONTENT_W - 18);
    const sign = tutorFirst ? run(`— ${tutorFirst}`, fonts.reg, 10.5, 15, C.soft, CONTENT_W - 18) : null;
    heading(`A note from ${tutorFirst || "your tutor"}`, Math.min(r.height, 36));
    // Line by line, so a long note can carry over to the next page.
    r.lines.forEach((line) => {
      ensure(r.lh);
      page.drawRectangle({ x: MARGIN, y: H - y - r.lh, width: 3, height: r.lh, color: C.sky });
      drawRun(page, { ...r, lines: [line], height: r.lh }, MARGIN + 18, y);
      y += r.lh;
    });
    if (sign) {
      y += 6;
      ensure(sign.height);
      drawRun(page, sign, MARGIN + 18, y);
      y += sign.height;
    }
  }

  // ---- Footer on every page ----
  const pages = doc.getPages();
  pages.forEach((p, i) => {
    p.drawRectangle({ x: MARGIN, y: 46, width: CONTENT_W, height: 0.75, color: C.line });
    const left = sanitize(`Prepared by ${opts.tutorName} with BumbleNote`, fonts.reg);
    p.drawText(left, { x: MARGIN, y: 30, size: 8.5, font: fonts.reg, color: C.muted });
    const right = `Page ${i + 1} of ${pages.length}`;
    p.drawText(right, {
      x: W - MARGIN - fonts.reg.widthOfTextAtSize(right, 8.5),
      y: 30,
      size: 8.5,
      font: fonts.reg,
      color: C.muted,
    });
  });

  return doc.save();
}
