// Packs the lesson-report PDF's fonts and logo into src/lib/pdf-assets.ts as
// base64, so src/lib/pdf.ts can embed them without reading files at runtime
// (the server bundle on Netlify doesn't reliably carry loose asset files).
//
//   npx tsx scripts/build-pdf-assets.ts
//
// Re-run after changing anything in assets/pdf/ or public/logo-lockup.png.
// Fonts are the site's own, Fraunces and Hanken Grotesk, as static TTF
// instances from Google Fonts (both SIL Open Font License, see assets/pdf/OFL.txt).

import { readFileSync, writeFileSync } from "fs";

const ASSETS: Record<string, string> = {
  frauncesRegular: "assets/pdf/Fraunces-Regular.ttf",
  frauncesItalic: "assets/pdf/Fraunces-Italic.ttf",
  hankenRegular: "assets/pdf/HankenGrotesk-Regular.ttf",
  hankenBold: "assets/pdf/HankenGrotesk-Bold.ttf",
  hankenItalic: "assets/pdf/HankenGrotesk-Italic.ttf",
  logoLockup: "public/logo-lockup.png",
};

const lines = Object.entries(ASSETS).map(
  ([name, path]) => `export const ${name} = "${readFileSync(path).toString("base64")}";`,
);

writeFileSync(
  "src/lib/pdf-assets.ts",
  `// Generated by scripts/build-pdf-assets.ts. Do not edit by hand.\n/* eslint-disable */\n\n${lines.join("\n\n")}\n`,
);
console.log(`Wrote src/lib/pdf-assets.ts (${Object.keys(ASSETS).length} assets).`);
